### PR TITLE
Add arm64 build

### PR DESCRIPTION
**Pull request by Phoenix09**
Tested and working on my Galaxy S6.

The app would need updating to handle this.

### CODE REVIEW

**Comment by meefik** [comment]
What NDK version needed for success compile?
```
miscutils/lib.a(time.o): In function `run_command':
time.c:(.text.run_command+0x80): undefined reference to `wait3'
collect2: error: ld returned 1 exit status
```

**Comment by Phoenix09** [comment]
I was using NDK 11, see #8  
also see: 52c15521a40fd578d15cd2c4831eafac302456a1
which was fixed in busybox 1.24.2: 4c70ad7714890e459809a11d41de31535f247a52

I just recompiled it with 11c, will test 12b soon

**Comment by meefik** [comment]
On r10d and r12b with CONFIG_TIME=y an error..

**Comment by Phoenix09** [comment]
I see, it fails on arm builds but not arm64
@NHellFire, help?

**Comment by Phoenix09** [comment]
`wait3()` was removed from the NDK
patch: https://github.com/NHellFire/busybox-android-ndk/blob/master/patches/052-wait3.patch

**Comment by Phoenix09** [comment]
actually, a better fix would be replace the wait3 call with wait4

**Comment by NHellFire** [comment]
I've updated my patch to just call wait4 directly

**Comment by meefik** [comment]
Thanks, it works!

**Pull request merged**
